import React from 'react';
import Link from 'next/link';
import { ArrowLeft, Zap, Orbit, Lightbulb } from 'lucide-react';

export default function RegenTheoryPage() {
  return (
    <div className="w-full h-full overflow-y-auto bg-black p-8 md:p-12 flex justify-center">
      <article className="max-w-3xl w-full text-neutral-300 flex flex-col gap-10 pb-20">
        
        <div className="flex flex-col gap-6 border-b border-neutral-800 pb-8 mt-4">
          <Link href="/regen" className="inline-flex items-center gap-2 text-sm text-neutral-400 hover:text-blue-400 transition-colors w-fit">
            <ArrowLeft className="w-4 h-4" />
            Back to Simulation
          </Link>
          <div className="flex items-center justify-between">
            <h1 className="text-4xl md:text-5xl font-bold text-white tracking-tight">Regenerative Braking</h1>
            <div className="p-3 bg-red-500/10 rounded-xl border border-red-500/20">
              <Orbit className="w-8 h-8 text-red-400" />
            </div>
          </div>
        </div>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-2">
            <Lightbulb className="w-5 h-5 text-yellow-500" /> Core Concept
          </h2>
          <p className="leading-relaxed text-lg text-neutral-400">
            Regenerative braking is an energy recovery mechanism that slows down a moving vehicle by converting its kinetic energy into a form that can be either used immediately or stored until needed.
          </p>
          

[Image of regenerative braking system in electric vehicle]

        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-6">How It Works</h2>
          <div className="grid gap-4">
            <div className="bg-neutral-900/50 border border-neutral-800 p-6 rounded-xl">
              <h3 className="text-lg font-medium text-blue-400 mb-2">1. The Motor as a Generator</h3>
              <p className="leading-relaxed text-neutral-400 text-sm">
                In an EV, the electric motor can run in two directions. When you press the accelerator, it consumes electricity to create torque. When you lift off the pedal, the forward momentum of the wheels physically forces the motor to spin, turning it into a generator.
              </p>
            </div>
            <div className="bg-neutral-900/50 border border-neutral-800 p-6 rounded-xl">
              <h3 className="text-lg font-medium text-green-400 mb-2">2. Energy Recovery</h3>
              <p className="leading-relaxed text-neutral-400 text-sm">
                The mechanical resistance of the motor acting as a generator is what slows the car down. The electrical energy generated by this resistance is routed backwards into the battery pack, actively recharging it while driving.
              </p>
            </div>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4">Physics Equation</h2>
          <div className="bg-neutral-900 border border-neutral-800 p-6 rounded-xl font-mono text-sm overflow-x-auto">
            <p className="text-neutral-500 mb-3 uppercase tracking-wider text-xs">Recoverable Kinetic Energy:</p>
            <p className="text-white text-lg tracking-wider font-serif italic">
              E<sub>k</sub> = &frac12; mv<sup>2</sup> &times; &eta;
            </p>
            <p className="text-neutral-500 mt-4 text-xs">Where <i>m</i> is mass, <i>v</i> is velocity, and <i>&eta;</i> is the system efficiency (usually ~60-70%).</p>
          </div>
        </section>

        <section>
          <h2 className="text-2xl font-semibold text-white mb-4 flex items-center gap-2">
            <Zap className="w-5 h-5 text-blue-500" /> Real-World Relevance
          </h2>
          <p className="leading-relaxed text-neutral-400">
            Regenerative braking significantly extends the range of an EV (up to 20% in city driving) and drastically reduces the physical wear and tear on traditional friction brake pads.
          </p>
        </section>

      </article>
    </div>
  );
}